name: dogcat
batch_size: 32
initial_lr: 0.1
momentum: 0.9
weight_declay: 0.0001
epochs: 90
data_folder: /home/bzhou/Data/dogcat
model: densenet161
pretrain: True
num_classes: 2
train_val_split: 0.8
regime:
  0: 0.1
  30: 0.01
  90: 0.001

